//Posting users into users table when user signs-up

POST http://localhost:3001/users
Content-Type: application/json

{
    "name":"Sasanka",
    "age":21,
    "mobile_no":"9494344363",
    "email":"sasanka.g@westagilelabs.com",
    "password":"sasanka123"
}

